Distinguish between mesh and time series
SeisSol/Visualization pull request #7
Opened 2021-12-21 16:53 UTC by sebwolf-de

2022-07-07 19:19 UTC, ravil-mobile commented
shall it be merged?

2022-07-07 19:32 UTC, ravil-mobile commented
There is a problem in this branch with naming [seissolxmdf](https://github.com/SeisSol/Visualization/tree/sebastian/xdmfwriter/seissolxmdf)

Please, pay attention to the spelling. Everything is ok in the master branch

2022-07-08 07:10 UTC, Thomas-Ulrich requested changes

2022-07-08 07:10 UTC, Thomas-Ulrich commented on seissolxdmfwriter/seissolxdmfwriter/seissolxdmfwriter.py
> +    if len(lidt) == 1:
Can we use instead 
```if  (dt == 0):```
I it may occur that there is only one item in lIdt but we still want to keep the time information.

2023-10-10 13:34 UTC, Thomas-Ulrich approved these changes

2023-10-10 13:35 UTC, Thomas-Ulrich commented
I've added my proposed change before merging

2023-10-10 13:35 UTC, merged